/* Receitas extraídas de "Receitas favoritas.docx" e
   "Receitas favoritas — complementos (emagrecimento).docx".
   Receitas muito parecidas foram mescladas e aparecem como variações.
   Vídeos do playlist do YouTube entram como receita nova ou como variação
   quando parecida_com aponta para um id já existente. */

const CATEGORIAS = [
  "Pratos principais",
  "Entradas e pastas",
  "Pães e tortas",
  "Biscoitos e crackers",
  "Doces e lanches",
  "Café da manhã",
  "Barras de cereais",
];

const RECEITAS = [
  {
    id: "nhoque-banana-da-terra",
    titulo: "Nhoque de Banana-da-Terra",
    categoria: "Pratos principais",
    tags: [],
    icone: "imagens/receita-icon-banana.jpg",
    destaque: "Cozinhar a banana com casca para manter a consistência.",
    ingredientes: [
      {
        itens: [
          "4 bananas-da-terra maduras (com casca)",
          "1 xícara de farinha de trigo (ou farinha de arroz)",
          "1 gema de ovo",
          "1 colher de sopa de manteiga",
          "Sal e noz-moscada a gosto",
        ],
      },
    ],
    preparo: [
      "Lave as bananas e cozinhe-as inteiras com a casca em água fervente até ficarem macias.",
      "Retire as cascas, amasse as bananas ainda quentes até obter um purê liso e deixe esfriar.",
      "Adicione a gema, a manteiga, o sal e a noz-moscada. Misture bem.",
      "Acrescente a farinha aos poucos até atingir a consistência ideal para modelar.",
      "Faça rolinhos sobre uma superfície enfarinhada e corte os nhoques.",
      "Cozinhe em água fervente com sal até subirem à superfície. Sirva com o molho de sua preferência.",
    ],
    dicas: [
      "Para um toque especial, doure os nhoques na manteiga com sálvia antes de servir.",
      "Podem ser congelados antes do cozimento.",
    ],
    nutricao: { kcal: 280, prot: 6, carb: 52, gord: 6 },
    compras: [
      { secao: "Hortifrúti", itens: ["4 bananas-da-terra maduras"] },
      { secao: "Laticínios e ovos", itens: ["1 ovo", "Manteiga"] },
      { secao: "Mercearia", itens: ["Farinha de trigo ou de arroz (1 xícara)"] },
      { secao: "Temperos", itens: ["Sal", "Noz-moscada"] },
    ],
  },
  {
    id: "file-mignon-suino-jabuticaba",
    titulo: "Filé Mignon Suíno com Molho de Jabuticaba",
    categoria: "Pratos principais",
    tags: [],
    icone: "imagens/receita-icon-pork.jpg",
    destaque: "Selagem rápida da carne para manter a suculência.",
    ingredientes: [
      {
        itens: [
          "600 g de filé mignon suíno cortado em medalhões",
          "2 dentes de alho picados",
          "1 colher de sopa de azeite de oliva",
          "200 g de jabuticabas frescas (ou geleia concentrada de jabuticaba)",
          "1/2 xícara de vinho tinto seco",
          "1 colher de sopa de mel",
          "Sal e pimenta-do-reino a gosto",
        ],
      },
    ],
    preparo: [
      "Tempere os medalhões de filé mignon suíno com alho, sal e pimenta-do-reino.",
      "Aqueça bem uma frigideira com azeite e sele a carne rapidamente de ambos os lados para manter a suculência interna.",
      "Na mesma frigideira, adicione as jabuticabas maceradas, o vinho tinto e o mel.",
      "Cozinhe em fogo baixo até o molho reduzir e encorpar.",
      "Cubra os medalhões com o molho e sirva a seguir.",
    ],
    dicas: [
      "Se não encontrar jabuticabas frescas, use geleia sem açúcar diluída em um pouco de água ou caldo de carne.",
    ],
    nutricao: { kcal: 310, prot: 32, carb: 18, gord: 11 },
    compras: [
      { secao: "Hortifrúti", itens: ["200 g de jabuticabas (ou geleia de jabuticaba)", "1 cabeça de alho"] },
      { secao: "Carnes e peixes", itens: ["600 g de filé mignon suíno"] },
      { secao: "Mercearia", itens: ["Vinho tinto seco (1/2 xícara)", "Mel", "Azeite de oliva"] },
      { secao: "Temperos", itens: ["Sal", "Pimenta-do-reino"] },
    ],
  },
  {
    id: "lombo-porco-ervas-agridoce",
    titulo: "Lombo de Porco com Ervas e Molho Agridoce de Tomate",
    categoria: "Pratos principais",
    tags: [],
    icone: "imagens/receita-icon-pork.jpg",
    destaque: "Assado com ervas frescas e pincelado com molho agridoce de tomate.",
    ingredientes: [
      {
        itens: [
          "1 kg de lombo de porco",
          "Ervas frescas a gosto (alecrim, tomilho, sálvia e manjericão)",
          "3 dentes de alho amassados",
          "Suco de 1 limão",
          "1 xícara de extrato de tomate artesanal",
          "2 colheres de sopa de açúcar mascavo ou mel",
          "2 colheres de sopa de vinagre de maçã",
          "Azeite, sal e pimenta a gosto",
        ],
      },
    ],
    preparo: [
      "Tempere o lombo com o suco de limão, alho, sal, pimenta e as ervas frescas bem picadas. Deixe marinando por 1 hora.",
      "Em uma panela pequena, misture o extrato de tomate, o açúcar mascavo e o vinagre de maçã. Cozinhe em fogo baixo até formar um molho agridoce levemente espesso.",
      "Sele a peça no azeite, transfira para uma assadeira, cubra com papel-alumínio e leve ao forno pré-aquecido a 180 °C por 40 minutos.",
      "Retire o alumínio, pincele o molho agridoce e asse por mais 15 a 20 minutos até dourar.",
    ],
    dicas: [
      "Acompanha perfeitamente purê de batatas ou legumes assados.",
      "Deixe a carne descansar 5 minutos antes de fatiar.",
    ],
    nutricao: { kcal: 340, prot: 38, carb: 14, gord: 15 },
    compras: [
      {
        secao: "Hortifrúti",
        itens: ["Alecrim, tomilho, sálvia e manjericão frescos", "1 cabeça de alho", "1 limão"],
      },
      { secao: "Carnes e peixes", itens: ["1 kg de lombo de porco"] },
      {
        secao: "Mercearia",
        itens: [
          "Extrato de tomate (1 xícara)",
          "Açúcar mascavo ou mel",
          "Vinagre de maçã",
          "Azeite de oliva",
          "Papel-alumínio",
        ],
      },
      { secao: "Temperos", itens: ["Sal", "Pimenta-do-reino"] },
    ],
  },
  {
    id: "medalhoes-camarao",
    titulo: "Medalhões de Camarão",
    categoria: "Pratos principais",
    tags: ["Low-carb"],
    icone: "imagens/receita-icon-shrimp.jpg",
    destaque: "Selagem e grelha rápidas para suculência e textura.",
    ingredientes: [
      {
        itens: [
          "500 g de camarões limpos e grandes",
          "2 colheres de sopa de azeite de oliva",
          "2 dentes de alho picados fino",
          "Suco de 1/2 limão-siciliano",
          "Salsinha e cebolinha frescas picadas",
          "Sal e pimenta-do-reino a gosto",
        ],
      },
    ],
    preparo: [
      "Tempere os camarões com alho, suco de limão, sal e pimenta-do-reino.",
      "Molde os camarões em formato circular (medalhões).",
      "Aqueça uma frigideira ou grelha com azeite em fogo alto.",
      "Grelhe por aproximadamente 2 a 3 minutos de cada lado para manter a suculência e a textura.",
      "Finalize com ervas frescas e sirva morno.",
    ],
    dicas: ["Sirva sobre uma cama de risoto de limão-siciliano ou salada verde refrescante."],
    nutricao: { kcal: 220, prot: 28, carb: 3, gord: 10 },
    compras: [
      {
        secao: "Hortifrúti",
        itens: ["1 limão-siciliano", "1 cabeça de alho", "Salsinha", "Cebolinha"],
      },
      { secao: "Carnes e peixes", itens: ["500 g de camarões grandes limpos"] },
      { secao: "Mercearia", itens: ["Azeite de oliva"] },
      { secao: "Temperos", itens: ["Sal", "Pimenta-do-reino"] },
    ],
  },
  {
    id: "escondidinho-cabotia-carne-seca",
    titulo: "Escondidinho de Abóbora Cabotiá e Carne-Seca",
    categoria: "Pratos principais",
    tags: ["Sem glúten"],
    icone: "imagens/receita-icon-pumpkin.jpg",
    destaque: "Purê de abóbora cabotiá com recheio de carne-seca, gratinado no forno.",
    ingredientes: [
      {
        itens: [
          "600 g de abóbora cabotiá descascada e picada",
          "400 g de carne-seca dessalgada, cozida e desfiada",
          "1 cebola grande fatiada",
          "2 dentes de alho picados",
          "2 colheres de sopa de requeijão ou queijo cremoso",
          "100 g de queijo parmesão ralado",
          "Azeite, sal e pimenta a gosto",
        ],
      },
    ],
    preparo: [
      "Cozinhe a abóbora cabotiá até ficar bem macia, amasse em forma de purê e misture com o requeijão cremoso.",
      "Em uma frigideira, refogue a cebola e o alho no azeite com a carne-seca desfiada.",
      "Em um refratário, faça uma camada de purê, adicione o recheio de carne-seca e cubra com o restante do purê.",
      "Polvilhe queijo ralado e leve ao forno pré-aquecido a 200 °C até gratinar.",
    ],
    dicas: [
      "A carne-seca pode ser substituída por frango desfiado ou cogumelos para uma versão vegetariana.",
    ],
    nutricao: { kcal: 360, prot: 24, carb: 28, gord: 18 },
    compras: [
      {
        secao: "Hortifrúti",
        itens: ["600 g de abóbora cabotiá", "1 cebola grande", "1 cabeça de alho"],
      },
      { secao: "Carnes e peixes", itens: ["400 g de carne-seca"] },
      {
        secao: "Laticínios e ovos",
        itens: ["Requeijão ou queijo cremoso", "100 g de queijo parmesão ralado"],
      },
      { secao: "Mercearia", itens: ["Azeite de oliva"] },
      { secao: "Temperos", itens: ["Sal", "Pimenta-do-reino"] },
    ],
  },
  {
    id: "burrata-tomates-manjericao",
    titulo: "Burrata com Tomates e Manjericão",
    categoria: "Entradas e pastas",
    tags: ["Low-carb", "Sem glúten"],
    icone: "imagens/receita-icon-tomato-basil.jpg",
    destaque: "Montada com tomates frescos ou confitados e manjericão.",
    ingredientes: [
      {
        itens: [
          "1 peça de burrata fresca",
          "200 g de tomates-cereja ou tomates italianos maduros",
          "Folhas de manjericão fresco",
          "3 colheres de sopa de azeite de oliva extravirgem",
          "1 colher de sopa de redução de balsâmico",
          "Flor de sal (ou sal grosso) e pimenta-do-reino a gosto",
        ],
      },
    ],
    preparo: [
      "Corte os tomates e arranje-os em uma travessa.",
      "Acomode a burrata inteira no centro do prato.",
      "Adicione as folhas de manjericão ao redor.",
      "Regue com azeite de oliva extravirgem e redução de balsâmico.",
      "Tempere com flor de sal e pimenta-do-reino.",
    ],
    dicas: [
      "Retire a burrata da geladeira 20 minutos antes de servir para garantir máxima cremosidade.",
      "Acompanhe com torradas artesanais.",
    ],
    nutricao: { kcal: 390, prot: 16, carb: 8, gord: 32 },
    compras: [
      {
        secao: "Hortifrúti",
        itens: ["200 g de tomates-cereja ou italianos", "1 maço de manjericão"],
      },
      { secao: "Laticínios e ovos", itens: ["1 burrata fresca"] },
      {
        secao: "Mercearia",
        itens: ["Azeite de oliva extravirgem", "Redução de balsâmico", "Torradas artesanais (opcional)"],
      },
      { secao: "Temperos", itens: ["Flor de sal ou sal grosso", "Pimenta-do-reino"] },
    ],
  },
  {
    id: "biscoitos-grao-de-bico",
    titulo: "Biscoitos Crocantes de Grão-de-Bico",
    categoria: "Biscoitos e crackers",
    tags: ["Sem glúten", "Vegana"],
    icone: "imagens/receita-icon-chickpea-cracker.jpg",
    destaque: "Lanche nutritivo e crocante, feito com farinha de grão-de-bico.",
    ingredientes: [
      {
        itens: [
          "1 xícara de farinha de grão-de-bico",
          "3 colheres de sopa de azeite de oliva",
          "3 a 4 colheres de sopa de água morna",
          "1 colher de chá de sementes (gergelim ou chia)",
          "1/2 colher de chá de páprica defumada",
          "Sal a gosto",
        ],
      },
    ],
    preparo: [
      "Misture a farinha de grão-de-bico, as sementes, a páprica e o sal em uma tigela.",
      "Adicione o azeite e a água aos poucos até formar uma massa homogênea.",
      "Abra a massa bem fina entre folhas de papel-manteiga.",
      "Corte os biscoitos e coloque-os em uma assadeira.",
      "Asse a 180 °C por 15 a 20 minutos até ficarem bem crocantes.",
    ],
    dicas: [
      "Guarde em pote hermético por até 1 semana para manter a crocância.",
      "Ótima opção de snack para o dia a dia.",
    ],
    nutricao: { kcal: 140, prot: 5, carb: 16, gord: 6 },
    compras: [
      {
        secao: "Mercearia",
        itens: [
          "Farinha de grão-de-bico (1 xícara)",
          "Gergelim ou chia",
          "Azeite de oliva",
          "Papel-manteiga",
        ],
      },
      { secao: "Temperos", itens: ["Páprica defumada", "Sal"] },
    ],
  },
  {
    id: "pizza-de-aveia",
    titulo: "Pizza de Aveia",
    categoria: "Pães e tortas",
    tags: [],
    icone: "imagens/receita-icon-cheese.jpg",
    destaque: "Base de aveia pré-assada para ficar estruturada.",
    ingredientes: [
      {
        itens: [
          "1 xícara de farinha de aveia ou aveia em flocos finos",
          "1 ovo",
          "1/2 xícara de água",
          "1 colher de chá de fermento em pó",
          "Sal e orégano a gosto",
          "Molho de tomate, queijo muçarela e manjericão para a cobertura",
        ],
      },
    ],
    preparo: [
      "Bata o ovo com a aveia, a água, o sal e o orégano. Adicione o fermento por último.",
      "Espalhe a massa numa frigideira untada ou forma de pizza.",
      "Pré-asse a massa até firmar a estrutura.",
      "Adicione o molho, o queijo e o recheio desejado.",
      "Derreta o queijo no fogo ou no forno e sirva a seguir.",
    ],
    variacoes: [
      {
        id: "pao-frigideira-ovo-abobrinha-aveia",
        titulo: "Pão de frigideira de ovo, abobrinha e aveia",
        categoria: "Pães e tortas",
        ingredientes: [
          {
            itens: [
              "2 ovos",
              "2 colheres (sopa) de cenoura ralada",
              "2 colheres (sopa) de batatinha ralada",
              "2 colheres (sopa) de abobrinha ralada",
              "3 colheres de sopa de aveia",
              "1 colher de sopa de queijo parmesão",
              "Pimenta-do-reino a gosto",
              "Sal a gosto",
              "1 colher (chá) de fermento em pó",
            ],
          },
        ],
        preparo: [
          "Misture todos os ingredientes em uma tigela até obter uma massa homogênea.",
          "Despeje na frigideira antiaderente (untuada se necessário) e doure dos dois lados até cozinhar por completo.",
        ],
        fonte: { texto: "YouTube — PARE DE Comer OVO FRITO!Misture 2 OVOS e ABOBRINHA e Você vai Viciar nessa Delícia PÃO de FRIGIDEIRA", url: "https://www.youtube.com/watch?v=cIJioO7oDLg" },
        destaque: "Pão de frigideira leve com ovos, abobrinha, cenoura e aveia — pronto em minutos.",
        dicas: [
          "Serve bem no café da manhã ou como lanche rápido.",
        ],
      },
      {
        id: "pao-achatado-cottage-aveia",
        titulo: "Pão achatado de cottage com farinha de aveia",
        categoria: "Pães e tortas",
        ingredientes: [
          {
            itens: [
              "1 xícara de queijo cottage",
              "1/2 xícara de farinha de aveia (ou farinha de preferência)",
              "1 ovo",
              "1/4 xícara de parmesão (Parmigiano Reggiano) — opcional/extra",
              "Sal a gosto",
              "Azeite para untar",
            ],
          },
        ],
        preparo: [
          "Misture cottage, farinha de aveia, ovo, parmesão (se usar) e sal até formar uma massa.",
          "Forre uma assadeira com papel manteiga, unte com azeite e espalhe a massa com cerca de 0,5–1 cm de espessura.",
          "Asse até dourar e ficar crocante (conforme o vídeo, em poucos minutos em forno quente).",
          "Use para sanduíches, tacos, dips ou lanchar puro.",
        ],
        fonte: { texto: "YouTube — How To Make Cottage Cheese Flatbread", url: "https://www.youtube.com/watch?v=Yyzdcpqct50" },
        destaque: "Flatbread proteico com cottage, ovo e farinha de aveia — pronto em cerca de 10 minutos.",
        dicas: [
          "Sem fermento e sem espera de crescimento.",
        ],
      },
    ],
    dicas: [
      "Para uma massa mais crocante, deixe assar por 5 minutos de cada lado na frigideira antes de colocar o recheio.",
    ],
    nutricao: { kcal: 320, prot: 14, carb: 36, gord: 13 },
    compras: [
      { secao: "Hortifrúti", itens: ["Manjericão fresco"] },
      { secao: "Laticínios e ovos", itens: ["1 ovo", "Queijo muçarela"] },
      {
        secao: "Mercearia",
        itens: ["Farinha de aveia ou aveia em flocos finos (1 xícara)", "Fermento em pó", "Molho de tomate"],
      },
      { secao: "Temperos", itens: ["Sal", "Orégano"] },
    ],
  },
  {
    id: "cookies-banana-aveia",
    titulo: "Cookies de Banana e Aveia",
    categoria: "Doces e lanches",
    tags: ["Sem açúcar"],
    icone: "imagens/receita-icon-oat-cookie.jpg",
    destaque: "Uma única base de banana madura e aveia, com três variações: fit com chia, com iogurte ou com chocolate na airfryer.",
    ingredientes: [
      {
        titulo: "Base",
        itens: [
          "2 bananas maduras (nanicas ou médias)",
          "1 xícara (≈120 g) de aveia em flocos finos ou farinha de aveia",
          "1 colher de chá de canela em pó",
          "1 pitada de sal",
        ],
      },
    ],
    preparo: [
      "Amasse bem as bananas com um garfo até formar um purê homogêneo.",
      "Acrescente a aveia, a canela e o sal, misturando até que a aveia absorva a umidade e vire uma massa moldável.",
      "Junte os ingredientes da variação escolhida (veja abaixo).",
      "Com uma colher, modele bolinhas, dê uma leve achatada e disponha em assadeira forrada com papel-manteiga.",
      "Asse conforme a variação até as bordas dourarem. Espere esfriar para firmar.",
    ],
    variacoes: [
      {
        nome: "Fit com chia",
        descricao: "Baixas calorias, rico em fibras e sem adição de açúcar ou gorduras.",
        itens: ["+ 1 colher de sopa de sementes de chia ou linhaça (opcional)"],
        passos: ["Asse em forno preaquecido a 180 °C por 15 a 20 minutos."],
        nutricao: { kcal: 110, prot: 3, carb: 21, gord: 2 },
      },
      {
        nome: "Com iogurte natural",
        descricao: "Massa mais macia, enriquecida com iogurte.",
        itens: [
          "Use só 1 banana (ou 2 colheres de sopa de mel)",
          "+ 1/2 xícara de iogurte natural integral",
          "+ 1/2 colher de chá de fermento em pó",
          "+ gotas de chocolate amargo ou castanhas (opcional)",
        ],
        passos: [
          "Misture a banana amassada com o iogurte antes de juntar a aveia; o fermento entra junto com a aveia.",
          "Asse a 180 °C por 15 a 20 minutos.",
        ],
        nutricao: { kcal: 150, prot: 5, carb: 24, gord: 4 },
      },
      {
        nome: "Com chocolate na airfryer",
        descricao: "Só 3 ingredientes: banana, aveia e chocolate.",
        itens: ["+ 40 g de gotas de chocolate (preferencialmente amargo)", "Canela e sal são opcionais aqui"],
        passos: ["Asse na airfryer pré-aquecida a 180 °C por cerca de 10 a 12 minutos."],
        nutricao: { kcal: 160, prot: 4, carb: 26, gord: 5 },
      },
      {
        id: "cookies-aveia-nuts-sem-acucar",
        titulo: "Cookies de aveia e mix de nuts sem farinha nem açúcar",
        categoria: "Doces e lanches",
        ingredientes: [
          {
            itens: [
              "200 g de amendoim",
              "60 g de avelãs (torrar e descascar)",
              "30 g de sementes de abóbora",
              "1 colher de sopa de sementes de girassol",
              "1 colher de sopa de gergelim",
              "30 g de cranberries secas (preiselbeeren)",
              "20 g de passas",
              "20 g de castanha de caju",
              "50 g de nozes",
              "120 g de aveia em flocos",
              "1 ovo (ou 1 ovo de linhaça, versão vegana)",
              "30 ml de xarope de bordo",
              "Para variação de docinhos: 80 g de chocolate amargo sem açúcar (e parte das nuts reservadas para pasta)",
            ],
          },
        ],
        preparo: [
          "Torre e prepare as nuts conforme o vídeo; reserve uma parte das nozes para pasta/cobertura.",
          "Misture amendoim, avelãs, sementes, frutas secas, caju, nozes, aveia, ovo (ou ovo de linhaça) e xarope de bordo.",
          "Unte moldes ou forme cookies (~8 cm); asse a 180 °C por cerca de 20 minutos.",
          "Variação docinhos: triture parte das nuts reservadas até virar pasta, misture com chocolate amargo derretido, acomode em forma de silicone e decore; leve a esfriar/geladeira.",
          "Deixe os cookies esfriarem completamente antes de guardar.",
        ],
        fonte: { texto: "YouTube — Kein Zucker! Gesunde Kekse ohne Mehl, Zucker und Gluten! Energiedessert für jeden Tag!", url: "https://www.youtube.com/watch?v=mdPveC7HlFM" },
        destaque: "Cookies energéticos de aveia e oleaginosas, adoçados com xarope de bordo — sem farinha nem açúcar refinado.",
        dicas: [
          "O vídeo mostra cookies e também docinhos de pasta de nuts com chocolate a partir dos mesmos ingredientes.",
          "Versão vegana: troque o ovo por ovo de linhaça.",
        ],
      },
    ],
    dicas: [
      "Polvilhe canela por cima antes de assar para destacar o aroma da banana.",
      "Uma pitada de noz-moscada ou raspas de limão também aromatizam a massa.",
      "Pedaços de nozes ou castanhas dão mais textura a qualquer variação.",
    ],
    compras: [
      { secao: "Hortifrúti", itens: ["2 bananas bem maduras"] },
      { secao: "Laticínios e ovos", itens: ["Iogurte natural integral (variação com iogurte)"] },
      {
        secao: "Mercearia",
        itens: [
          "Aveia em flocos finos (120 g)",
          "Chia ou linhaça (variação fit, opcional)",
          "Fermento em pó (variação com iogurte)",
          "Gotas de chocolate amargo, 40 g (variação airfryer)",
          "Castanhas ou nozes (opcional)",
          "Papel-manteiga",
        ],
      },
      { secao: "Temperos", itens: ["Canela em pó", "Sal"] },
    ],
  },
  {
    id: "muffins-mirtilo",
    titulo: "Muffins de Mirtilo",
    categoria: "Doces e lanches",
    tags: [],
    icone: "imagens/receita-icon-yogurt-berries.jpg",
    destaque: "Muffins fofos e úmidos com mirtilos frescos.",
    ingredientes: [
      {
        itens: [
          "1 e 1/2 xícara de farinha de trigo",
          "1/2 xícara de açúcar",
          "1/2 xícara de leite",
          "1/4 de xícara de óleo de coco ou manteiga derretida",
          "1 ovo",
          "1 xícara de mirtilos frescos",
          "1 colher de sopa de fermento em pó",
          "1 colher de chá de essência de baunilha",
        ],
      },
    ],
    preparo: [
      "Em um recipiente, misture o ovo, o açúcar, o leite, o óleo de coco e a baunilha.",
      "Adicione a farinha de trigo e misture delicadamente.",
      "Incorpore os mirtilos e, por último, o fermento em pó.",
      "Distribua a massa em forminhas de muffin e asse em forno pré-aquecido a 180 °C por cerca de 20 a 25 minutos.",
    ],
    dicas: [
      "Passe os mirtilos em um pouco de farinha antes de juntar à massa para que não afundem na fôrma.",
    ],
    nutricao: { kcal: 210, prot: 4, carb: 32, gord: 8 },
    compras: [
      { secao: "Hortifrúti", itens: ["1 xícara de mirtilos frescos"] },
      { secao: "Laticínios e ovos", itens: ["1 ovo", "Leite (1/2 xícara)", "Manteiga (se não usar óleo de coco)"] },
      {
        secao: "Mercearia",
        itens: [
          "Farinha de trigo (1 e 1/2 xícara)",
          "Açúcar (1/2 xícara)",
          "Óleo de coco",
          "Fermento em pó",
          "Essência de baunilha",
          "Forminhas de muffin",
        ],
      },
    ],
  },
  {
    id: "pate-shiitake-tomate-seco",
    titulo: "Patê de Shiitake com Tomate Seco",
    categoria: "Entradas e pastas",
    tags: ["Low-carb"],
    icone: "imagens/receita-icon-mushroom.jpg",
    destaque: "Cogumelos refogados no azeite com alho, processados com tomate seco e cream cheese ou ricota.",
    ingredientes: [
      {
        itens: [
          "200 g de cogumelos shiitake frescos fatiados",
          "100 g de tomate seco picado",
          "150 g de cream cheese ou ricota fresca",
          "2 dentes de alho picados",
          "2 colheres de sopa de azeite de oliva",
          "1 colher de sopa de molho shoyu",
          "Sal, pimenta-do-reino e cheiro-verde a gosto",
        ],
      },
    ],
    preparo: [
      "Em uma frigideira, aqueça o azeite e refogue o alho até dourar levemente.",
      "Adicione o shiitake fatiado e o shoyu, refogando em fogo médio-alto até os cogumelos ficarem macios e dourados. Desligue e deixe esfriar um pouco.",
      "No processador ou liquidificador, adicione o shiitake refogado, o tomate seco e o cream cheese (ou ricota).",
      "Pulse até obter uma consistência homogênea e cremosa.",
      "Ajuste o sal e a pimenta-do-reino e misture o cheiro-verde picado.",
      "Leve à geladeira por pelo menos 30 minutos antes de servir.",
    ],
    dicas: [
      "Sirva com pães artesanais, torradas ou canapés.",
      "Conserve em geladeira por até 5 dias.",
    ],
    nutricao: { kcal: 180, prot: 4, carb: 9, gord: 14 },
    compras: [
      {
        secao: "Hortifrúti",
        itens: ["200 g de shiitake fresco", "1 cabeça de alho", "Cheiro-verde"],
      },
      { secao: "Laticínios e ovos", itens: ["150 g de cream cheese ou ricota fresca"] },
      { secao: "Mercearia", itens: ["100 g de tomate seco", "Molho shoyu", "Azeite de oliva"] },
      { secao: "Temperos", itens: ["Sal", "Pimenta-do-reino"] },
    ],
  },
  {
    id: "torta-ricota-legumes",
    titulo: "Torta Salgada de Ricota e Legumes (Massa Leve)",
    categoria: "Pães e tortas",
    tags: ["Low-carb"],
    icone: "imagens/receita-icon-eggs.jpg",
    destaque: "Massa aerada com claras em neve e um toque de farinha baixa em carboidratos.",
    ingredientes: [
      {
        titulo: "Massa",
        itens: [
          "3 ovos (claras e gemas separadas)",
          "200 g de ricota fresca bem amassada",
          "2 a 3 colheres de sopa (≈30 g) de farinha de aveia, de amêndoas ou Zaya",
          "1 colher de sopa de azeite ou manteiga derretida",
          "1 colher de chá rasa de fermento químico em pó",
          "Sal e pimenta-do-reino a gosto",
        ],
      },
      {
        titulo: "Recheio",
        itens: [
          "1 cebola fatiada",
          "200 g de cogumelos fatiados",
          "1 xícara de espinafre bem drenado",
          "1/2 pimentão em tiras",
          "Azeite, sal e pimenta a gosto",
        ],
      },
    ],
    preparo: [
      "Refogue a cebola, o pimentão, os cogumelos e o espinafre até ficarem macios e bem secos, sem excesso de água. Reserve para esfriar.",
      "Bata as 3 claras em neve firme.",
      "Em outra tigela, misture as gemas, a ricota, a farinha escolhida, o azeite, o sal e a pimenta até formar um creme homogêneo.",
      "Adicione o fermento e incorpore 1/3 das claras em neve para amaciar a mistura.",
      "Adicione o restante das claras delicadamente, com movimentos de baixo para cima, para manter o ar na massa.",
      "Em um refratário untado, espalhe metade da massa, adicione o recheio e cubra com o restante da massa.",
      "Asse em forno pré-aquecido a 180 °C por 25 a 30 minutos, até dourar levemente.",
    ],
    dicas: ["Varie os legumes do recheio usando abobrinha, cenoura ralada ou brócolis cozido al dente."],
    nutricao: { kcal: 230, prot: 14, carb: 12, gord: 14 },
    compras: [
      {
        secao: "Hortifrúti",
        itens: ["1 cebola", "200 g de cogumelos", "1 maço de espinafre", "1 pimentão"],
      },
      { secao: "Laticínios e ovos", itens: ["3 ovos", "200 g de ricota fresca"] },
      {
        secao: "Mercearia",
        itens: ["Farinha de aveia, de amêndoas ou Zaya (≈30 g)", "Fermento químico em pó", "Azeite de oliva"],
      },
      { secao: "Temperos", itens: ["Sal", "Pimenta-do-reino"] },
    ],
  },
  {
    id: "pao-cebola-sem-gluten",
    titulo: "Pão de Cebola Sem Glúten",
    categoria: "Pães e tortas",
    tags: ["Sem glúten"],
    icone: "imagens/receita-icon-olive-oil.jpg",
    destaque: "Massa de farinha de arroz, fécula de batata e psyllium, com cebola dourada lentamente.",
    ingredientes: [
      {
        titulo: "Massa",
        itens: [
          "1 xícara de farinha de arroz",
          "1/2 xícara de fécula de batata",
          "1 colher de sopa de psyllium",
          "1 colher de chá de sal",
          "5 g de fermento biológico seco",
          "1 colher de chá de açúcar",
          "1 ovo",
          "2 colheres de sopa de azeite de oliva",
          "3/4 de xícara de água morna",
          "1 colher de chá de vinagre de maçã",
        ],
      },
      {
        titulo: "Cebola",
        itens: [
          "1 cebola média em fatias finas",
          "1 colher de sopa de azeite de oliva",
          "1 pitada de sal",
          "1 colher de chá de ervas secas (orégano, tomilho ou alecrim)",
          "Gergelim para finalizar (opcional)",
        ],
      },
    ],
    preparo: [
      "Cebola: aqueça o azeite em fogo baixo, adicione a cebola e uma pitada de sal. Refogue lentamente por 12 a 15 minutos até dourar e amaciar. Desligue, misture as ervas e reserve.",
      "Fermento e secos: misture a água morna, o fermento e o açúcar e aguarde 5 minutos. Em outro recipiente, misture a farinha de arroz, a fécula, o psyllium e o sal.",
      "Massa: adicione o ovo, o azeite e o vinagre à mistura com fermento. Incorpore os secos aos poucos até obter uma massa homogênea, úmida e levemente pegajosa.",
      "Descanso: cubra a tigela e deixe descansar por 20 minutos (não precisa sovar).",
      "Montagem: unte uma forma pequena de pão ou forre com papel-manteiga. Espalhe metade da massa com uma colher umedecida, distribua parte da cebola e cubra com o restante da massa. Finalize com a cebola restante e o gergelim.",
      "Forno: deixe descansar mais 15 minutos enquanto aquece o forno a 180 °C. Asse por 30 a 35 minutos, até a superfície dourar e o pão firmar. Espere amornar antes de fatiar.",
    ],
    dicas: [
      "Pode ser congelado fatiado em sacos próprios para freezer.",
      "Para servir, basta aquecer na torradeira ou no forno.",
    ],
    nutricao: { kcal: 190, prot: 4, carb: 30, gord: 6 },
    compras: [
      { secao: "Hortifrúti", itens: ["1 cebola média"] },
      { secao: "Laticínios e ovos", itens: ["1 ovo"] },
      {
        secao: "Mercearia",
        itens: [
          "Farinha de arroz (1 xícara)",
          "Fécula de batata (1/2 xícara)",
          "Psyllium",
          "Fermento biológico seco (5 g)",
          "Açúcar",
          "Vinagre de maçã",
          "Azeite de oliva",
          "Gergelim (opcional)",
        ],
      },
      { secao: "Temperos", itens: ["Sal", "Ervas secas (orégano, tomilho ou alecrim)"] },
    ],
  },
  {
    id: "pasta-grao-de-bico-cogumelos-tahine",
    titulo: "Pasta Vegana de Grão-de-Bico e Cogumelos com Tahine",
    categoria: "Entradas e pastas",
    tags: ["Vegana", "Sem glúten"],
    icone: "imagens/receita-icon-mushroom.jpg",
    destaque: "Pasta rica em proteínas, cremosa e saudável para torradas.",
    ingredientes: [
      {
        itens: [
          "150 g de grão-de-bico (demolhado em água por 4 horas)",
          "8 cogumelos champignon frescos fatiados",
          "1 cebola picada",
          "3 dentes de alho picados",
          "3 colheres de sopa de tahine",
          "Suco de limão a gosto",
          "2 colheres de sopa de água gelada",
          "Salsinha fresca picada",
          "Azeite de oliva, sal e pimenta-do-reino a gosto",
        ],
      },
    ],
    preparo: [
      "Em uma frigideira com azeite, refogue a cebola picada até amolecer.",
      "Adicione os cogumelos e cozinhe junto com a cebola por cerca de 15 minutos, até dourarem e amaciarem.",
      "Cozinhe o grão-de-bico demolhado até ficar macio.",
      "No processador, adicione o grão-de-bico, os cogumelos e a cebola refogados, a salsinha, o tahine, o alho, o suco de limão e a água gelada.",
      "Bata até obter um creme completamente liso e homogêneo.",
      "Transfira para um pote de vidro. Sirva sobre torradas e finalize com salsinha e um fio de azeite.",
    ],
    dicas: ["Excelente opção de pasta proteica para lanches rápidos ou torradas integrais."],
    nutricao: { kcal: 170, prot: 7, carb: 16, gord: 9 },
    compras: [
      {
        secao: "Hortifrúti",
        itens: [
          "8 cogumelos champignon frescos",
          "1 cebola",
          "1 cabeça de alho",
          "1 limão",
          "Salsinha",
        ],
      },
      { secao: "Mercearia", itens: ["150 g de grão-de-bico seco", "Tahine", "Azeite de oliva"] },
      { secao: "Temperos", itens: ["Sal", "Pimenta-do-reino"] },
    ],
  },
  {
    id: "biscoitos-iogurte-maca",
    titulo: "Biscoitos de Iogurte e Maçã",
    categoria: "Doces e lanches",
    tags: [],
    icone: "imagens/receita-icon-oat-cookie.jpg",
    destaque: "Biscoitos macios e fáceis com maçã, iogurte, castanhas e gotas de chocolate.",
    ingredientes: [
      {
        itens: [
          "1 ovo",
          "1 pitada de sal",
          "80 g de açúcar",
          "Essência de baunilha a gosto",
          "100 ml de óleo vegetal",
          "100 ml de iogurte natural",
          "400 g de farinha de trigo",
          "30 g de amêndoas picadas",
          "30 g de nozes picadas",
          "30 g de gotas de chocolate",
          "1 maçã em cubos pequenos",
          "10 g de fermento em pó",
          "Açúcar de confeiteiro para polvilhar (opcional)",
        ],
      },
    ],
    preparo: [
      "Em uma tigela grande, misture o ovo, o sal, o açúcar e a baunilha com um fouet até homogeneizar.",
      "Acrescente o óleo vegetal e bata novamente.",
      "Adicione o iogurte natural e misture bem.",
      "Incorpore a farinha, as amêndoas, as nozes, as gotas de chocolate, a maçã e o fermento.",
      "Misture com uma espátula e depois amasse com as mãos até obter uma massa macia e homogênea.",
      "Abra a massa sobre superfície enfarinhada ou papel-manteiga na espessura desejada e corte em quadrados ou retângulos.",
      "Disponha os biscoitos em assadeira forrada com papel-manteiga.",
      "Asse em forno pré-aquecido a 180 °C por cerca de 20 minutos.",
      "Retire do forno, polvilhe açúcar de confeiteiro e sirva.",
    ],
    variacoes: [
      {
        id: "cookies-aveia-iogurte-dinamarqueses",
        titulo: "Cookies dinamarqueses de aveia e iogurte",
        categoria: "Doces e lanches",
        ingredientes: [
          {
            itens: [
              "250 g de aveia",
              "1 xícara de iogurte",
              "1/2 colher de chá de bicarbonato de sódio",
              "Raspas de 1 limão",
              "40 g de manteiga",
              "2 colheres de sopa de xarope de bordo (maple syrup)",
            ],
          },
        ],
        preparo: [
          "Misture a aveia, o iogurte, o bicarbonato, as raspas de limão, a manteiga e o xarope de bordo até formar a massa.",
          "Modele os cookies e asse por 20 minutos a 180 °C.",
        ],
        fonte: { texto: "YouTube — Just oatmeal and yogurt! This Danish oatmeal cookie recipe is delicious", url: "https://www.youtube.com/watch?v=8y3AEMvtq68" },
        destaque: "Cookies de aveia com iogurte, raspas de limão e xarope de bordo — simples e aromáticos.",
      },
    ],
    dicas: ["A receita é inspirada nos biscotti italianos de iogurte."],
    fonte: { texto: "Vídeo original no YouTube", url: "https://www.youtube.com/watch?v=jBdSeMzHmAo" },
    nutricao: { kcal: 190, prot: 3, carb: 25, gord: 9 },
    compras: [
      { secao: "Hortifrúti", itens: ["1 maçã"] },
      { secao: "Laticínios e ovos", itens: ["1 ovo", "100 ml de iogurte natural"] },
      {
        secao: "Mercearia",
        itens: [
          "Farinha de trigo (400 g)",
          "Açúcar (80 g)",
          "Óleo vegetal (100 ml)",
          "30 g de amêndoas",
          "30 g de nozes",
          "30 g de gotas de chocolate",
          "Fermento em pó (10 g)",
          "Essência de baunilha",
          "Açúcar de confeiteiro (opcional)",
          "Papel-manteiga",
        ],
      },
      { secao: "Temperos", itens: ["Sal"] },
    ],
  },
  {
    id: "frango-grelhado-legumes-vapor",
    titulo: "Frango Grelhado com Legumes no Vapor",
    categoria: "Pratos principais",
    tags: ["Emagrecimento", "Sem glúten"],
    icone: "imagens/receita-icon-chicken.jpg",
    destaque: "Proteína magra com bastante volume de vegetais e poucas calorias.",
    rendimento: "2 porções",
    ingredientes: [
      {
        itens: [
          "400 g de peito de frango",
          "1 abobrinha média em rodelas",
          "1 xícara de brócolis em floretes",
          "1 cenoura em palitos",
          "Suco de 1/2 limão",
          "1 dente de alho, páprica, sal e pimenta",
          "1 colher de chá de azeite",
          "Ervas (salsa, orégano)",
        ],
      },
    ],
    preparo: [
      "Tempere o frango com limão, alho, páprica, sal e pimenta e deixe descansar por 15 minutos.",
      "Grelhe ou asse a 200 °C com o azeite até cozinhar (cerca de 15 a 20 minutos).",
      "Cozinhe os legumes no vapor por 6 a 8 minutos, para ficarem crocantes.",
      "Finalize com ervas e sirva.",
    ],
    variacoes: [
      {
        id: "frango-gengibre-alho",
        titulo: "Frango com gengibre e alho na frigideira",
        categoria: "Pratos principais",
        ingredientes: [
          {
            titulo: "Marinada do frango",
            itens: [
              "2 peitos de frango grandes (600 g)",
              "1 colher de chá de gengibre fresco ralado",
              "1 colher de chá de alho ralado ou picado",
              "1 colher de sopa de molho de soja (shoyu)",
              "1 colher de sopa de azeite",
              "1 colher de sopa de mel",
              "1 colher de sopa de amido de milho",
              "1/2 colher de chá de sal",
              "1/3 colher de chá de flocos de pimenta (chili)",
              "Pimenta-do-reino a gosto",
            ],
          },
          {
            titulo: "Refogado",
            itens: [
              "4 colheres de sopa de azeite",
              "2 cebolas médias (300 g)",
              "3 pimentões (de preferência cores diferentes)",
              "1 colher de chá de gengibre ralado",
              "1 colher de chá de alho ralado",
              "1 cubo de caldo de frango",
              "100 ml de água quente (~1/3 xícara)",
              "1 colher de sopa de molho de soja",
              "1 colher de sopa de amido de milho",
              "Salsinha fresca picada para finalizar",
            ],
          },
          {
            titulo: "Arroz basmati (acompanhamento)",
            itens: [
              "300 g de arroz basmati",
              "1/2 colher de chá de sal",
              "1 colher de sopa de azeite ou manteiga",
              "450 ml de água fria (~2 xícaras)",
            ],
          },
        ],
        preparo: [
          "Corte o frango em pedaços, misture com os ingredientes da marinada, cubra e leve à geladeira por pelo menos 30 minutos (ou de um dia para o outro).",
          "Aqueça 4 colheres de sopa de azeite na frigideira e doure o frango em fogo alto por 4–5 minutos, virando; reserve.",
          "Na mesma panela, refogue as cebolas por 2 minutos; acrescente gengibre e alho por 1 minuto e depois os pimentões.",
          "Dissolva o cubo de caldo na água quente; misture shoyu e amido; despeje na panela e cozinhe até engrossar levemente.",
          "Volte o frango à panela, finalize com salsinha e sirva (com arroz basmati, se desejar).",
        ],
        fonte: { texto: "YouTube — The Ginger Garlic Chicken I Make on My Busiest Days! One Pan, Big Flavor", url: "https://www.youtube.com/watch?v=j1EUg_IfTh8" },
        destaque: "Frango marinado em gengibre, alho, shoyu e mel, refogado com pimentões — pronto em cerca de 20 minutos.",
        dicas: [
          "Coxas de frango também funcionam e ficam mais suculentas.",
          "Sirva com arroz, noodles, quinoa ou wrap.",
        ],
      },
      {
        id: "frango-mel-alho",
        titulo: "Frango ao mel e alho",
        categoria: "Pratos principais",
        ingredientes: [
          {
            itens: [
              "2 peitos de frango",
              "Sal a gosto",
              "Pimenta-do-reino a gosto",
              "Farinha de trigo (para empanar levemente)",
              "40 g de manteiga (para fritar o frango)",
              "3 dentes de alho",
              "Cebolinha",
              "20 g de manteiga (para o molho)",
              "1 colher de sopa de molho de soja light",
              "1 colher de sopa de vinagre",
              "5 colheres de sopa de mel",
            ],
          },
        ],
        preparo: [
          "Tempere os peitos com sal e pimenta; passe na farinha.",
          "Frite em ~40 g de manteiga em fogo médio por 4–5 minutos de cada lado; acrescente alho picado e cebolinha, virando conforme necessário.",
          "Adicione mais ~20 g de manteiga, o alho picado, 1 colher de shoyu light, 1 colher de vinagre e 5 colheres de mel; envolva o frango no molho.",
          "Finalize com cebolinha e sirva.",
        ],
        fonte: { texto: "YouTube — Honey garlic chicken ! Dinner ready in 15 minutes", url: "https://www.youtube.com/watch?v=dRW3VMfNlaY" },
        destaque: "Peito de frango dourado no molho de mel, alho, shoyu e vinagre — jantar em cerca de 15 minutos.",
      },
    ],
    dicas: [
      "Peito de frango sem pele já é magro; evite empanar.",
      "Temperos ácidos (limão, vinagre) aumentam o sabor sem calorias.",
      "Sobras: fatie para uma salada no dia seguinte.",
      "Se precisar de carboidrato, acrescente 3 colheres de sopa de arroz integral.",
    ],
    nutricao: { kcal: 245, prot: 42, carb: 10, gord: 5, fibras: 4 },
    compras: [
      {
        secao: "Hortifrúti",
        itens: [
          "1 abobrinha média",
          "1 maço de brócolis",
          "1 cenoura",
          "1 limão",
          "1 cabeça de alho",
          "Salsa",
        ],
      },
      { secao: "Carnes e peixes", itens: ["400 g de peito de frango"] },
      { secao: "Mercearia", itens: ["Azeite de oliva"] },
      { secao: "Temperos", itens: ["Páprica", "Orégano", "Sal", "Pimenta-do-reino"] },
    ],
  },
  {
    id: "salmao-assado-aspargos",
    titulo: "Salmão Assado com Aspargos",
    categoria: "Pratos principais",
    tags: ["Emagrecimento", "Low-carb", "Sem glúten"],
    icone: "imagens/receita-icon-salmon.jpg",
    destaque: "Ômega-3 e saciedade com porção de peixe controlada.",
    rendimento: "2 porções",
    ingredientes: [
      {
        itens: [
          "300 g de salmão em 2 postas",
          "300 g de aspargos (ou vagem + brócolis)",
          "1 colher de chá de azeite",
          "Raspas e suco de 1/2 limão",
          "Alho, dill (endro), sal e pimenta",
        ],
      },
    ],
    preparo: [
      "Forre a assadeira e acomode o salmão e os aspargos.",
      "Regue com azeite, limão e temperos.",
      "Asse a 200 °C por 12 a 15 minutos.",
    ],
    variacoes: [
      {
        id: "salmao-creme-espinafre-tomate",
        titulo: "Salmão ao creme com espinafre e tomate",
        categoria: "Pratos principais",
        ingredientes: [
          {
            itens: [
              "Salmão (cortado em pedaços, sem pele)",
              "Sal e pimenta a gosto",
              "1 cebola",
              "2 dentes de alho (mais 2 dentes no molho)",
              "Azeite",
              "12 tomates pequenos (cortados ao meio)",
              "Vinho branco seco",
              "200 g de espinafre",
              "300 ml de creme de leite (Sahne)",
              "2 colheres de sopa de parmesão",
              "Massa (macarrão) para acompanhar",
            ],
          },
        ],
        preparo: [
          "Corte o salmão em pedaços, retire a pele e tempere com sal e pimenta dos dois lados.",
          "Aqueça azeite na frigideira e sele o peixe 2 minutos de cada lado em fogo alto; reserve.",
          "Refogue a cebola; adicione vinho branco seco e deixe evaporar; acrescente alho.",
          "Refogue o espinafre por ~3 minutos; junte os tomates e cozinhe mais ~2 minutos.",
          "Adicione 300 ml de creme e 2 colheres de sopa de parmesão; volte o peixe à panela e cozinhe ~10 minutos em fogo baixo.",
          "Sirva com macarrão.",
        ],
        fonte: { texto: "YouTube — Ich habe noch nie so leckeren Fisch gegessen! Delikat, das auf der Zunge zergeht!", url: "https://www.youtube.com/watch?v=eCazTN5-Rsc" },
        destaque: "Salmão selado em molho cremoso de espinafre, tomate, vinho branco e parmesão.",
      },
    ],
    dicas: [
      "150 g de salmão por pessoa já basta: peixe gorduroso é calórico.",
      "Prefira assar ou grelhar a fritar.",
      "Acompanhe com folhas cruas para dar volume.",
      "Salmão congelado, descongelado na geladeira, funciona igual.",
    ],
    nutricao: { kcal: 320, prot: 30, carb: 6, gord: 20, fibras: 3 },
    compras: [
      {
        secao: "Hortifrúti",
        itens: ["300 g de aspargos (ou vagem e brócolis)", "1 limão", "1 cabeça de alho", "Dill (endro)"],
      },
      { secao: "Carnes e peixes", itens: ["2 postas de salmão (300 g)"] },
      { secao: "Mercearia", itens: ["Azeite de oliva"] },
      { secao: "Temperos", itens: ["Sal", "Pimenta-do-reino"] },
    ],
  },
  {
    id: "omelete-claras-espinafre-cogumelos",
    titulo: "Omelete de Claras com Espinafre e Cogumelos",
    categoria: "Café da manhã",
    tags: ["Emagrecimento", "Low-carb", "Sem glúten"],
    icone: "imagens/receita-icon-eggs.jpg",
    destaque: "Café da manhã ou jantar hiperproteico e baixo em calorias.",
    rendimento: "1 porção",
    ingredientes: [
      {
        itens: [
          "4 claras (ou 3 claras + 1 ovo inteiro)",
          "1 xícara de espinafre",
          "4 cogumelos fatiados",
          "1 colher de sopa de cebola picada",
          "Sal, pimenta e noz-moscada",
          "Spray de azeite ou 1/2 colher de chá de azeite",
        ],
      },
    ],
    preparo: [
      "Refogue a cebola e os cogumelos e junte o espinafre até murchar.",
      "Bata as claras com os temperos e despeje na frigideira antiaderente.",
      "Quando firmar, dobre e sirva.",
    ],
    dicas: [
      "Claras aumentam a proteína mantendo as calorias baixas.",
      "Se sentir fome cedo, use 3 claras + 1 gema.",
      "Acompanhe com tomate e 1 fatia de pão integral (opcional).",
      "Prepare os vegetais na noite anterior para agilizar.",
    ],
    nutricao: { kcal: 140, prot: 22, carb: 5, gord: 3, fibras: 2 },
    compras: [
      { secao: "Hortifrúti", itens: ["1 maço de espinafre", "4 cogumelos", "1 cebola"] },
      { secao: "Laticínios e ovos", itens: ["4 ovos"] },
      { secao: "Mercearia", itens: ["Azeite em spray ou azeite de oliva"] },
      { secao: "Temperos", itens: ["Sal", "Pimenta-do-reino", "Noz-moscada"] },
    ],
  },
  {
    id: "salada-atum-grao-de-bico",
    titulo: "Salada de Atum com Grão-de-Bico",
    categoria: "Pratos principais",
    tags: ["Emagrecimento", "Sem glúten"],
    icone: "imagens/receita-icon-salad.jpg",
    destaque: "Almoço rápido, barato e rico em proteína e fibras.",
    rendimento: "2 porções",
    ingredientes: [
      {
        itens: [
          "1 lata (120 g drenado) de atum em água",
          "1 xícara (160 g) de grão-de-bico cozido",
          "1 pepino picado",
          "1 tomate picado",
          "1/4 de cebola roxa",
          "Folhas a gosto (rúcula ou alface)",
          "Suco de 1 limão",
          "1 colher de chá de azeite",
          "Mostarda, sal e pimenta",
        ],
      },
    ],
    preparo: [
      "Escorra bem o atum e o grão-de-bico.",
      "Misture tudo com o limão, o azeite e a mostarda.",
      "Ajuste o sal e sirva gelado.",
    ],
    variacoes: [
      {
        id: "pasta-atum-abacate",
        titulo: "Pasta de atum e abacate proteica",
        categoria: "Pratos principais",
        ingredientes: [
          {
            titulo: "Creme de abacate",
            itens: [
              "2 abacates",
              "1 cebola roxa",
              "180 g de atum em água (suco próprio)",
              "2 ovos cozidos",
              "2 colheres de sopa de suco de limão",
            ],
          },
          {
            titulo: "Molho",
            itens: [
              "1 colher de sopa de iogurte grego",
              "0,3 colher de chá de pimenta-do-reino moída",
              "Sal a gosto",
              "1 colher de chá de suco de limão",
            ],
          },
        ],
        preparo: [
          "Prepare o creme misturando abacate, cebola roxa, atum, ovos cozidos e suco de limão.",
          "Tempere com o molho de iogurte grego, pimenta, sal e mais um pouco de limão.",
          "Sirva sobre pão tostado (conforme o vídeo).",
        ],
        fonte: { texto: "YouTube — High Protein Tuna Avocado Spread for Breakfast | Quick & Easy Breakfast for Work", url: "https://www.youtube.com/watch?v=WAwcloRLMY0" },
        destaque: "Pasta cremosa de abacate com atum e ovo — alta em proteína, ótima no pão.",
        dicas: [
          "Ideal para café da manhã ou lanche para o trabalho.",
        ],
      },
    ],
    dicas: [
      "Prefira atum em água, nunca em óleo.",
      "Se usar grão-de-bico enlatado, lave-o para reduzir o sódio.",
      "Leve em pote para o trabalho: aguenta bem algumas horas na geladeira.",
      "Dispensa o pão: a fibra do grão-de-bico já sacia.",
    ],
    nutricao: { kcal: 260, prot: 26, carb: 24, gord: 7, fibras: 7 },
    compras: [
      {
        secao: "Hortifrúti",
        itens: ["1 pepino", "1 tomate", "1 cebola roxa", "Rúcula ou alface", "1 limão"],
      },
      {
        secao: "Mercearia",
        itens: [
          "1 lata de atum em água",
          "Grão-de-bico cozido (160 g) ou em lata",
          "Mostarda",
          "Azeite de oliva",
        ],
      },
      { secao: "Temperos", itens: ["Sal", "Pimenta-do-reino"] },
    ],
  },
  {
    id: "sopa-creme-abobrinha-frango",
    titulo: "Sopa Creme de Abobrinha e Frango Desfiado",
    categoria: "Pratos principais",
    tags: ["Emagrecimento", "Sem glúten"],
    icone: "imagens/receita-icon-soup.jpg",
    destaque: "Jantar quente, baixo em calorias e com alta saciedade.",
    rendimento: "3 porções",
    ingredientes: [
      {
        itens: [
          "3 abobrinhas médias",
          "250 g de peito de frango cozido e desfiado",
          "1 cebola",
          "2 dentes de alho",
          "500 ml de caldo de legumes sem sal",
          "1 colher de chá de azeite",
          "Sal, pimenta e cheiro-verde",
        ],
      },
    ],
    preparo: [
      "Refogue a cebola e o alho no azeite, junte a abobrinha picada e o caldo.",
      "Cozinhe até amaciar e bata parte no liquidificador (deixe pedaços, se preferir).",
      "Volte à panela, acrescente o frango desfiado e aqueça. Finalize com ervas.",
    ],
    dicas: [
      "Dispense o creme de leite: a abobrinha batida já fica cremosa.",
      "Congela bem em porções individuais.",
      "Para engrossar, bata 1 colher de sopa de aveia junto.",
      "Jantar leve: 1 porção + salada.",
    ],
    nutricao: { kcal: 180, prot: 24, carb: 12, gord: 4, fibras: 3 },
    compras: [
      {
        secao: "Hortifrúti",
        itens: ["3 abobrinhas médias", "1 cebola", "1 cabeça de alho", "Cheiro-verde"],
      },
      { secao: "Carnes e peixes", itens: ["250 g de peito de frango"] },
      { secao: "Mercearia", itens: ["Caldo de legumes sem sal (500 ml)", "Azeite de oliva"] },
      { secao: "Temperos", itens: ["Sal", "Pimenta-do-reino"] },
    ],
  },
  {
    id: "bowl-quinoa-frango-legumes",
    titulo: "Bowl de Quinoa com Frango e Legumes",
    categoria: "Pratos principais",
    tags: ["Emagrecimento", "Sem glúten"],
    icone: "imagens/receita-icon-chicken.jpg",
    destaque: "Refeição completa para o pós-treino ou um almoço equilibrado.",
    rendimento: "2 porções",
    ingredientes: [
      {
        itens: [
          "1/2 xícara (90 g) de quinoa crua",
          "300 g de peito de frango",
          "1 xícara de brócolis",
          "1/2 pimentão",
          "1 cenoura ralada",
          "Folhas verdes",
          "1 colher de chá de azeite, limão e temperos",
        ],
      },
    ],
    preparo: [
      "Cozinhe a quinoa (1 parte de quinoa para 2 de água) e tempere.",
      "Grelhe o frango temperado e corte em tiras.",
      "Cozinhe ou salteie levemente os legumes.",
      "Monte o bowl com quinoa, frango, legumes e folhas. Regue com limão e azeite.",
    ],
    dicas: [
      "Quinoa traz proteína e fibras; meça a quantidade crua.",
      "3/4 do bowl devem ser vegetais e frango, com a quinoa no fundo.",
      "Prepare a quinoa e o frango no batch cooking de domingo.",
      "Evite molhos prontos: limão, mostarda e ervas bastam.",
    ],
    nutricao: { kcal: 340, prot: 38, carb: 32, gord: 7, fibras: 6 },
    compras: [
      {
        secao: "Hortifrúti",
        itens: ["1 maço de brócolis", "1 pimentão", "1 cenoura", "Folhas verdes", "1 limão"],
      },
      { secao: "Carnes e peixes", itens: ["300 g de peito de frango"] },
      { secao: "Mercearia", itens: ["Quinoa (90 g)", "Azeite de oliva"] },
      { secao: "Temperos", itens: ["Sal", "Pimenta-do-reino"] },
    ],
  },
  {
    id: "iogurte-proteico-chia-frutas-vermelhas",
    titulo: "Iogurte Proteico com Chia e Frutas Vermelhas",
    categoria: "Café da manhã",
    tags: ["Emagrecimento", "Sem glúten"],
    icone: "imagens/receita-icon-yogurt-berries.jpg",
    destaque: "Café da manhã ou lanche pronto em 5 minutos.",
    rendimento: "1 porção",
    ingredientes: [
      {
        itens: [
          "170 g de iogurte natural grego light (ou iogurte proteico)",
          "1 colher de sopa de sementes de chia",
          "80 g de frutas vermelhas (morango, mirtilo, framboesa)",
          "Canela a gosto",
          "5 g de castanhas picadas (opcional)",
        ],
      },
    ],
    preparo: [
      "Misture o iogurte e a chia e deixe hidratar por 5 a 10 minutos.",
      "Cubra com as frutas e a canela e finalize com as castanhas, se usar.",
    ],
    dicas: [
      "A chia aumenta as fibras e prolonga a saciedade.",
      "Evite granola industrial açucarada.",
      "Prepare de véspera na geladeira: vira um tipo de pudim.",
      "Se usar iogurte comum, acrescente 1 scoop de whey sem sabor (opcional).",
    ],
    nutricao: { kcal: 190, prot: 18, carb: 16, gord: 5, fibras: 6 },
    compras: [
      { secao: "Hortifrúti", itens: ["80 g de frutas vermelhas (morango, mirtilo, framboesa)"] },
      { secao: "Laticínios e ovos", itens: ["170 g de iogurte grego light ou proteico"] },
      { secao: "Mercearia", itens: ["Sementes de chia", "Castanhas (opcional)"] },
      { secao: "Temperos", itens: ["Canela em pó"] },
    ],
  },
  {
    id: "hamburguer-peru-salada",
    titulo: "Hambúrguer de Peru com Salada",
    categoria: "Pratos principais",
    tags: ["Emagrecimento", "Low-carb", "Sem glúten"],
    icone: "imagens/receita-icon-salad.jpg",
    destaque: "Hambúrguer magro servido sobre salada, sem pão.",
    rendimento: "2 hambúrgueres (2 porções)",
    ingredientes: [
      {
        itens: [
          "300 g de carne moída de peru (ou frango)",
          "1/2 cebola ralada e bem espremida",
          "1 dente de alho",
          "1 clara de ovo (se necessário para dar liga)",
          "Salsinha, sal, páprica e pimenta",
          "Salada: folhas, tomate e pepino",
          "1 colher de chá de azeite para grelhar",
        ],
      },
    ],
    preparo: [
      "Misture a carne com a cebola, o alho e os temperos e forme 2 discos.",
      "Grelhe por 4 a 5 minutos de cada lado.",
      "Sirva sobre a salada (sem pão) ou com 1/2 pão integral.",
    ],
    dicas: [
      "Sem pão, o “hambúrguer bowl” corta muitas calorias.",
      "Não amasse demais a carne: ela fica mais suculenta.",
      "Evite queijo e maionese; use mostarda e iogurte temperado.",
      "Congele crus, separados por papel-manteiga.",
    ],
    nutricao: { kcal: 220, prot: 32, carb: 4, gord: 8, fibras: 1 },
    compras: [
      {
        secao: "Hortifrúti",
        itens: ["1 cebola", "1 cabeça de alho", "Salsinha", "Folhas para salada", "1 tomate", "1 pepino"],
      },
      { secao: "Carnes e peixes", itens: ["300 g de carne moída de peru (ou frango)"] },
      { secao: "Laticínios e ovos", itens: ["1 ovo"] },
      { secao: "Mercearia", itens: ["Azeite de oliva", "Pão integral (opcional)"] },
      { secao: "Temperos", itens: ["Páprica", "Sal", "Pimenta-do-reino"] },
    ],
  },
  {
    id: "peixe-ensopado-leve",
    titulo: "Peixe Ensopado Leve",
    categoria: "Pratos principais",
    tags: ["Emagrecimento", "Low-carb", "Sem glúten"],
    icone: "imagens/receita-icon-soup.jpg",
    destaque: "Uma “moqueca light”, sem leite de coco integral.",
    rendimento: "3 porções",
    ingredientes: [
      {
        itens: [
          "500 g de peixe branco firme (tilápia, merluza ou badejo)",
          "1 cebola em rodelas",
          "1 pimentão em tiras",
          "2 tomates picados",
          "2 dentes de alho",
          "200 ml de leite de coco light (ou 150 ml de água de coco + 1 colher de chá de azeite)",
          "Coentro ou salsa, limão, sal e pimenta",
          "Páprica ou colorau",
        ],
      },
    ],
    preparo: [
      "Tempere o peixe com limão, sal e pimenta.",
      "Refogue a cebola, o alho e o pimentão; junte o tomate e a páprica.",
      "Acrescente o líquido, acomode o peixe e cozinhe tampado por 10 a 12 minutos.",
      "Finalize com as ervas.",
    ],
    dicas: [
      "O leite de coco light reduz bastante a gordura em relação ao tradicional.",
      "Sirva com 2 colheres de arroz integral ou só com legumes.",
      "Peixe congelado funciona bem; seque antes de temperar.",
      "Ótimo para batch cooking: reaquece sem ressecar.",
    ],
    nutricao: { kcal: 240, prot: 32, carb: 8, gord: 9, fibras: 2 },
    compras: [
      {
        secao: "Hortifrúti",
        itens: ["1 cebola", "1 pimentão", "2 tomates", "1 cabeça de alho", "Coentro ou salsa", "1 limão"],
      },
      { secao: "Carnes e peixes", itens: ["500 g de peixe branco (tilápia, merluza ou badejo)"] },
      { secao: "Mercearia", itens: ["Leite de coco light (200 ml) ou água de coco", "Azeite de oliva"] },
      { secao: "Temperos", itens: ["Páprica ou colorau", "Sal", "Pimenta-do-reino"] },
    ],
  },
  {
    id: "overnight-oats-proteico",
    titulo: "Overnight Oats Proteico",
    categoria: "Café da manhã",
    tags: ["Emagrecimento"],
    icone: "imagens/receita-icon-yogurt-berries.jpg",
    destaque: "Café da manhã pronto, sem fogo e cheio de fibras.",
    rendimento: "1 porção",
    ingredientes: [
      {
        itens: [
          "40 g de aveia em flocos",
          "150 ml de leite desnatado ou bebida vegetal sem açúcar",
          "100 g de iogurte natural light",
          "1 colher de sopa de chia",
          "1/2 scoop (≈10–15 g) de whey ou 1 clara pasteurizada (opcional)",
          "Canela e 80 g de fruta (maçã ou morango)",
        ],
      },
    ],
    preparo: [
      "Misture a aveia, o leite, o iogurte, a chia e a proteína (se usar) num pote.",
      "Leve à geladeira por no mínimo 4 horas (o ideal é passar a noite).",
      "De manhã, acrescente a fruta e a canela.",
    ],
    dicas: [
      "Meça a aveia: é o ponto que mais estoura as calorias quando vai “no olho”.",
      "Sem whey, o iogurte grego light já ajuda na proteína.",
      "Não adicione mel se a fruta estiver doce.",
      "Prepare 3 potes de uma vez para a semana (a fruta só na hora).",
    ],
    nutricao: { kcal: 310, prot: 28, carb: 38, gord: 6, fibras: 8 },
    compras: [
      { secao: "Hortifrúti", itens: ["80 g de maçã ou morango"] },
      {
        secao: "Laticínios e ovos",
        itens: ["Leite desnatado ou bebida vegetal sem açúcar (150 ml)", "100 g de iogurte natural light"],
      },
      { secao: "Mercearia", itens: ["Aveia em flocos (40 g)", "Chia", "Whey protein (opcional)"] },
      { secao: "Temperos", itens: ["Canela em pó"] },
    ],
  },
  {
    id: "chips-crocantes-queijo",
    titulo: "Chips Crocantes de Queijo",
    categoria: "Biscoitos e crackers",
    tags: ["Low-carb", "Sem glúten"],
    icone: "imagens/receita-icon-cheese.jpg",
    destaque: "Crocância com quase zero carboidrato, em duas versões: parmesão ou mussarela.",
    rendimento: "2 porções (snack) · carboidrato líquido ≈ 1–2 g por porção",
    ingredientes: [
      {
        titulo: "Base",
        itens: [
          "80 a 100 g de queijo ralado (veja a variação)",
          "Páprica, orégano ou pimenta-do-reino a gosto",
        ],
      },
    ],
    preparo: [
      "Pré-aqueça o forno a 180 °C e forre a assadeira (ou a cesta da airfryer) com papel-manteiga.",
      "Faça montinhos pequenos de queijo bem espaçados, ou espalhe em discos finos de cerca de 5 cm.",
      "Polvilhe os temperos levemente.",
      "Asse até dourar e as bordas firmarem, sem deixar queimar (tempo na variação).",
      "Esfrie na assadeira sem mexer: os chips endurecem ao esfriar.",
    ],
    variacoes: [
      {
        nome: "Parmesão",
        descricao: "O mais crocante e com menos carboidrato.",
        itens: ["80 g de queijo parmesão ralado fino (sem amido no rótulo)"],
        passos: ["Forno: 6 a 10 minutos.", "Airfryer: 160–170 °C por 5 a 7 minutos, olhando de perto."],
        nutricao: { kcal: 160, prot: 14, carb: 1, gord: 11, fibras: 0 },
      },
      {
        nome: "Mussarela",
        descricao: "Alternativa aos chips de batata, com quase zero amido.",
        itens: ["100 g de mussarela ralada (de preferência low moisture, com pouco soro)"],
        passos: [
          "Forno: 7 a 12 minutos.",
          "Airfryer: 170 °C por 5 a 8 minutos.",
          "Se soltar óleo, escorra em papel-toalha depois de frio.",
        ],
        nutricao: { kcal: 150, prot: 11, carb: 2, gord: 11, fibras: 0 },
      },
      {
        id: "salgadinho-batata-doce-parmesao",
        titulo: "Salgadinho de batata-doce com parmesão e gergelim",
        categoria: "Biscoitos e crackers",
        ingredientes: [
          {
            itens: [
              "1 xícara (250 g) de batata-doce cozida e amassada",
              "1 colher de sopa (13 ml) de azeite de oliva",
              "1/2 colher de chá (2 g) de sal",
              "1/4 de xícara (30 g) de mix de farinha sem glúten (ou amido de milho / polvilho doce / farinha de trigo)",
              "60 g de queijo parmesão ralado",
              "3 colheres de sopa (24 g) de gergelim",
            ],
          },
        ],
        preparo: [
          "Cozinhe a batata-doce até ficar macia, escorra e amasse (ou processe) até virar purê — use 1 xícara / 250 g.",
          "Em uma tigela, misture a batata-doce, o azeite, o sal e o mix de farinha sem glúten até formar massa que não grude nas mãos.",
          "Incorpore o parmesão ralado e o gergelim.",
          "Faça bolinhas de cerca de 14 g, distribua em assadeira forrada com papel manteiga (espaço de ~4 cm) e achate com a base de um copo e um pedaço de papel manteiga (quanto mais fino, mais crocante).",
          "Asse em forno pré-aquecido a 180 °C por cerca de 30 minutos, até secar e dourar levemente nas bordas.",
          "Deixe esfriar completamente e guarde em pote hermético.",
        ],
        fonte: { texto: "YouTube — SALGADINHO SAUDÁVEL DE BATATA DOCE COM PARMESÃO SEM GLÚTEN | Cook'n Enjoy 1857", url: "https://www.youtube.com/watch?v=FbzjVvVyCEM" },
        destaque: "Snack crocante de batata-doce, parmesão e gergelim — sem glúten e assado.",
        dicas: [
          "Substituições sugeridas no vídeo: só amido de milho, polvilho doce ou farinha de trigo (1/4 xícara).",
          "Validade: cerca de 7 dias em pote fechado em local seco.",
        ],
        nutricao: "~32 kcal por unidade (segundo o site da receita)",
        rendimento: "cerca de 25 unidades",
      },
    ],
    dicas: [
      "Quase sem carboidrato; a limitação é a gordura do queijo, então meça cerca de 40 g por lanche.",
      "Use parmesão puro: misturas “para gratinar” costumam ter amido.",
      "Não empilhe os chips quentes, pois grudam e amolecem.",
      "Guarde em pote com papel-toalha, porque a umidade amolece.",
      "Faça as duas versões na mesma fornada para variar a textura.",
    ],
    compras: [
      {
        secao: "Laticínios e ovos",
        itens: ["80 g de parmesão ralado puro (versão parmesão)", "100 g de mussarela low moisture (versão mussarela)"],
      },
      { secao: "Mercearia", itens: ["Papel-manteiga", "Papel-toalha"] },
      { secao: "Temperos", itens: ["Páprica", "Orégano", "Pimenta-do-reino"] },
    ],
  },
  {
    id: "biscoitos-crocantes-oleaginosas",
    titulo: "Biscoitos Crocantes de Oleaginosas",
    categoria: "Biscoitos e crackers",
    tags: ["Low-carb", "Sem glúten"],
    icone: "imagens/receita-icon-nuts.jpg",
    destaque: "Biscoitos finos e crocantes de farinha de amêndoa ou de castanha de caju.",
    rendimento: "12 biscoitos (4 porções de 3) · carboidrato líquido ≈ 3–4 g por porção",
    ingredientes: [
      {
        titulo: "Base",
        itens: [
          "100 g de farinha de oleaginosa (veja a variação)",
          "Azeite, sal e ervas (conforme a variação)",
          "Pimenta-do-reino a gosto",
        ],
      },
    ],
    preparo: [
      "Misture todos os ingredientes da variação escolhida até formar uma massa maleável.",
      "Abra bem fino (cerca de 2 mm) entre dois papéis-manteiga.",
      "Corte em retângulos ou círculos e faça furinhos com um garfo.",
      "Asse até dourar nas bordas (temperatura e tempo na variação).",
      "Deixe esfriar na assadeira para terminar de endurecer.",
    ],
    variacoes: [
      {
        nome: "Amêndoa e ovo",
        descricao: "Pode ser salgado (alecrim e alho em pó) ou doce (canela e eritritol).",
        itens: [
          "100 g de farinha de amêndoas",
          "1 ovo",
          "1 colher de sopa de azeite ou manteiga derretida",
          "1/2 colher de chá de fermento em pó (sem amido, se possível)",
          "1/4 de colher de chá de sal",
          "1/2 colher de chá de alecrim ou páprica (opcional)",
          "Adoçante (stevia ou eritritol) só na versão doce",
        ],
        passos: [
          "Asse a 170 °C por 12 a 18 minutos.",
          "Desligue o forno e deixe 5 minutos com a porta entreaberta para secar mais.",
        ],
        nutricao: { kcal: 175, prot: 7, carb: 5, gord: 15, fibras: 2 },
      },
      {
        nome: "Castanha de caju e ervas",
        descricao: "Mais “gourmet”; a clara sem gema deixa o biscoito mais seco e crocante.",
        itens: [
          "100 g de castanha de caju crua, sem sal",
          "1 clara de ovo",
          "1 colher de chá de azeite",
          "1/2 colher de chá de sal",
          "1 colher de chá de ervas provençais ou alecrim",
        ],
        passos: [
          "Processe a castanha até virar uma farinha grossa, sem deixar virar pasta oleosa.",
          "Asse a 160 °C por 15 a 20 minutos.",
        ],
        nutricao: { kcal: 180, prot: 6, carb: 7, gord: 15, fibras: 1 },
      },
    ],
    dicas: [
      "Oleaginosas são calóricas: a porção é de 3 biscoitos, não a fornada.",
      "Quanto mais fino, mais crocante e menos “massa de cookie”.",
      "Pode trocar metade da castanha por amêndoa para baixar um pouco o carboidrato.",
      "Congela bem depois de assado; reaqueça 3 minutos a 160 °C para recuperar a crocância.",
      "Sirva com 1 colher de sopa do Patê de Shiitake com Tomate Seco.",
    ],
    compras: [
      { secao: "Laticínios e ovos", itens: ["1 ovo"] },
      {
        secao: "Mercearia",
        itens: [
          "100 g de farinha de amêndoas (versão amêndoa)",
          "100 g de castanha de caju crua sem sal (versão caju)",
          "Fermento em pó (versão amêndoa)",
          "Azeite de oliva",
          "Adoçante stevia ou eritritol (opcional, versão doce)",
          "Papel-manteiga",
        ],
      },
      {
        secao: "Temperos",
        itens: ["Sal", "Alecrim ou ervas provençais", "Páprica (opcional)", "Pimenta-do-reino"],
      },
    ],
  },
  {
    id: "crackers-sementes",
    titulo: "Crackers de Sementes",
    categoria: "Biscoitos e crackers",
    tags: ["Low-carb", "Sem glúten", "Vegana"],
    icone: "imagens/receita-icon-seeds.jpg",
    destaque: "Chia, linhaça e gergelim, quase sem farinha, com fibras altas.",
    rendimento: "4 porções · carboidrato líquido ≈ 2 g por porção",
    ingredientes: [
      {
        itens: [
          "3 colheres de sopa de chia",
          "3 colheres de sopa de linhaça moída",
          "2 colheres de sopa de gergelim",
          "1 colher de sopa de semente de girassol ou abóbora (opcional)",
          "150 ml de água",
          "1/4 de colher de chá de sal",
          "Páprica ou alho em pó a gosto",
        ],
      },
    ],
    preparo: [
      "Misture as sementes, o sal e os temperos com a água. Descanse 10 a 15 minutos, até virar um gel.",
      "Espalhe bem fino em assadeira com papel-manteiga (use outra folha por cima para alisar).",
      "Asse a 160 °C por 35 a 45 minutos; na metade do tempo, corte em quadrados e vire, se puder.",
      "Asse até estar seco e crocante. Esfrie completamente.",
    ],
    variacoes: [
      {
        id: "crackers-aveia-chia",
        titulo: "Crackers de aveia e chia",
        categoria: "Biscoitos e crackers",
        ingredientes: [
          {
            itens: [
              "1 xícara (90 g) de aveia em flocos triturada em farinha (ou 90 g de farinha de aveia)",
              "4 colheres de sopa (40 g) de sementes de chia",
              "3/4 xícara (~180 ml) de água",
              "1/4 colher de chá de sal",
              "1/2 colher de chá de fermento em pó (baking powder)",
              "1 colher de chá de orégano seco (ou outra erva/especiaria)",
              "Azeite nas mãos para modelar (se a massa grudar)",
            ],
          },
        ],
        preparo: [
          "Triture a aveia até virar farinha fina (ou use farinha de aveia pronta).",
          "Misture a chia com a água, cubra e deixe hidratar por 15–30 minutos.",
          "Adicione a farinha de aveia, o sal, o fermento e o orégano; misture até formar massa macia e levemente pegajosa (acrescente um pouco mais de farinha se precisar).",
          "Deixe a massa descansar 10–15 minutos; pré-aqueça o forno a 175 °C (340 °F).",
          "Divida em ~30 porções (~1/2 colher de sopa cada), forme bolinhas e coloque em assadeira forrada; achate com um copo e pedaço de papel até ~5 mm.",
          "Asse 15 minutos, vire cada cracker e asse mais 15 minutos até crocantes. Evite assar demais — endurecem ao esfriar. Esfrie completamente.",
        ],
        fonte: { texto: "YouTube — Just Oats & Chia Seeds! The Healthiest Snack You’ll Make This Week❗️", url: "https://www.youtube.com/watch?v=7P_4y4j9cWA" },
        destaque: "Crackers crocantes feitos basicamente com farinha de aveia e chia — leves e temperados com orégano.",
        dicas: [
          "Se a massa grudar ao modelar, passe um fio de azeite nas mãos.",
          "Bom com hummus, tzatziki ou guacamole.",
        ],
        nutricao: "Por cracker: ~19 kcal; 0,66 g proteína; 0,69 g gordura; 2,59 g carboidrato; 0,7 g fibra",
        rendimento: "cerca de 30 crackers",
      },
    ],
    dicas: [
      "Se amolecer no pote, reaqueça 5 a 8 minutos a 150 °C.",
      "Excelente com patê de ricota, cottage ou guacamole em porção medida.",
      "Não economize no tempo de forno: umidade significa biscoito mole.",
    ],
    nutricao: { kcal: 140, prot: 5, carb: 8, gord: 10, fibras: 6 },
    compras: [
      {
        secao: "Mercearia",
        itens: [
          "Chia",
          "Linhaça moída",
          "Gergelim",
          "Semente de girassol ou abóbora (opcional)",
          "Papel-manteiga",
        ],
      },
      { secao: "Temperos", itens: ["Sal", "Páprica ou alho em pó"] },
    ],
  },
  {
    id: "biscoitos-farinha-coco",
    titulo: "Biscoitos Salgados de Farinha de Coco",
    categoria: "Biscoitos e crackers",
    tags: ["Low-carb", "Sem glúten"],
    icone: "imagens/receita-icon-herbs.jpg",
    destaque: "O leve dulçor natural do coco combina com ervas salgadas.",
    rendimento: "10 biscoitos (5 porções de 2) · carboidrato líquido ≈ 2 g por porção",
    ingredientes: [
      {
        itens: [
          "40 g de farinha de coco",
          "2 ovos",
          "1 colher de sopa de azeite",
          "1/4 de colher de chá de sal",
          "1/2 colher de chá de fermento",
          "1 colher de chá de ervas finas ou orégano",
          "1 a 2 colheres de sopa de água (só se a massa ficar seca demais)",
        ],
      },
    ],
    preparo: [
      "Misture a farinha de coco, o sal, o fermento e as ervas.",
      "Junte os ovos e o azeite; ajuste com água até dar para abrir.",
      "Abra fino, corte e fure com um garfo.",
      "Asse a 170 °C por 12 a 15 minutos, até as bordas dourarem. Esfrie na grade.",
    ],
    dicas: [
      "A farinha de coco absorve muito líquido; não acrescente farinha de trigo “para corrigir”.",
      "Porção pequena: 2 biscoitos + queijo cottage.",
      "Guarde em pote hermético, com sachê absorvedor de umidade se tiver.",
    ],
    nutricao: { kcal: 110, prot: 5, carb: 5, gord: 8, fibras: 3 },
    compras: [
      { secao: "Laticínios e ovos", itens: ["2 ovos"] },
      { secao: "Mercearia", itens: ["Farinha de coco (40 g)", "Fermento em pó", "Azeite de oliva"] },
      { secao: "Temperos", itens: ["Sal", "Ervas finas ou orégano"] },
    ],
  },
  {
    id: "barra-aveia-amendoim-cacau",
    titulo: "Barra de Aveia, Pasta de Amendoim e Cacau",
    categoria: "Barras de cereais",
    tags: ["Emagrecimento", "Sem açúcar"],
    icone: "imagens/receita-icon-cereal-bar.jpg",
    destaque: "Lanche doce sem açúcar refinado, com fibra e gordura boa em porção controlada.",
    rendimento: "8 barras",
    ingredientes: [
      {
        itens: [
          "120 g de aveia em flocos",
          "2 bananas maduras amassadas (≈200 g)",
          "40 g de pasta de amendoim integral (100% amendoim)",
          "1 colher de sopa (≈8 g) de cacau em pó 100%",
          "1 colher de sopa de chia",
          "1 colher de chá de canela",
          "1 pitada de sal",
          "20 g de gotas de chocolate 70% (opcional)",
        ],
      },
    ],
    preparo: [
      "Pré-aqueça o forno a 170 °C. Forre uma forma pequena (cerca de 20×20 cm) com papel-manteiga.",
      "Misture a banana, a pasta de amendoim, o cacau, a canela e o sal até ficar homogêneo.",
      "Incorpore a aveia e a chia (e o chocolate, se usar).",
      "Espalhe na forma, compactando bem com as costas da colher.",
      "Asse por 18 a 22 minutos, até firmar e dourar levemente nas bordas.",
      "Esfrie completamente, corte em 8 barras e guarde na geladeira ou no freezer.",
    ],
    dicas: [
      "Meça a pasta de amendoim: é o item mais calórico.",
      "1 barra = 1 lanche.",
      "Sem banana bem madura a barra fica seca; não compense com mel.",
      "Congeladas duram semanas; descongele 5 minutos antes de comer.",
    ],
    nutricao: { kcal: 145, prot: 5, carb: 20, gord: 5, fibras: 4 },
    compras: [
      { secao: "Hortifrúti", itens: ["2 bananas bem maduras"] },
      {
        secao: "Mercearia",
        itens: [
          "Aveia em flocos (120 g)",
          "Pasta de amendoim integral (40 g)",
          "Cacau em pó 100%",
          "Chia",
          "Gotas de chocolate 70% (opcional)",
          "Papel-manteiga",
        ],
      },
      { secao: "Temperos", itens: ["Canela em pó", "Sal"] },
    ],
  },
  {
    id: "barra-proteica-whey-aveia-castanhas",
    titulo: "Barra Proteica de Whey, Aveia e Castanhas",
    categoria: "Barras de cereais",
    tags: ["Emagrecimento"],
    icone: "imagens/receita-icon-cereal-bar.jpg",
    destaque: "Sem forno: lanche hiperproteico para o pós-treino ou para segurar a fome.",
    rendimento: "8 barras",
    ingredientes: [
      {
        itens: [
          "80 g de aveia em flocos finos",
          "40 g de whey protein (baunilha ou sem sabor)",
          "30 g de castanhas picadas (amêndoa ou castanha-do-pará)",
          "2 colheres de sopa de pasta de amendoim ou tahine",
          "80 ml de leite desnatado ou água (ajuste a textura)",
          "1 colher de sopa de linhaça moída",
          "Canela ou essência de baunilha a gosto",
          "Adoçante (stevia ou eritritol) só se o whey não for doce o bastante",
        ],
      },
    ],
    preparo: [
      "Misture a aveia, o whey, as castanhas e a linhaça.",
      "Aqueça levemente a pasta de amendoim, misture ao líquido e junte aos secos até formar uma massa pegajosa que dê para prensar.",
      "Pressione firmemente numa forma forrada (cerca de 18×18 cm).",
      "Leve à geladeira por 2 horas (ou ao freezer por 45 minutos) até firmar.",
      "Corte em 8 barras. Guarde refrigeradas por até 5 dias ou congele.",
    ],
    dicas: [
      "Prefira whey isolado ou concentrado sem açúcar e sem cobertura de chocolate.",
      "Se a massa ficar mole, acrescente 1 colher de aveia, e não mais pasta.",
      "Ideal de 30 a 60 minutos após o treino, com café sem açúcar.",
      "Versão sem whey: troque por 40 g de leite em pó desnatado (a proteína fica um pouco menor).",
    ],
    nutricao: { kcal: 130, prot: 10, carb: 11, gord: 5, fibras: 2 },
    compras: [
      { secao: "Laticínios e ovos", itens: ["Leite desnatado (80 ml), ou use água"] },
      {
        secao: "Mercearia",
        itens: [
          "Aveia em flocos finos (80 g)",
          "Whey protein baunilha ou sem sabor (40 g)",
          "30 g de amêndoas ou castanhas-do-pará",
          "Pasta de amendoim ou tahine",
          "Linhaça moída",
          "Essência de baunilha (opcional)",
          "Adoçante stevia ou eritritol (opcional)",
          "Papel-manteiga",
        ],
      },
      { secao: "Temperos", itens: ["Canela em pó"] },
    ],
  },
  {
    id: "barra-crocante-aveia-sementes-mel",
    titulo: "Barra Crocante de Aveia, Sementes e Mel",
    categoria: "Barras de cereais",
    tags: ["Emagrecimento"],
    icone: "imagens/receita-icon-cereal-bar.jpg",
    destaque: "Crocância de barrinha industrial, com mel medido e muitas sementes.",
    rendimento: "10 barras",
    ingredientes: [
      {
        itens: [
          "140 g de aveia em flocos",
          "2 colheres de sopa de mel (≈40 g), ou eritritol + 1 colher de sopa de água",
          "2 colheres de sopa de azeite ou óleo de coco",
          "2 colheres de sopa de sementes mistas (girassol, abóbora, gergelim)",
          "1 colher de sopa de chia ou linhaça",
          "30 g de damasco seco picado ou cranberry sem açúcar (opcional, aumenta o carboidrato)",
          "1 colher de chá de essência de baunilha",
          "1 pitada de sal",
          "1/2 colher de chá de canela",
        ],
      },
    ],
    preparo: [
      "Pré-aqueça o forno a 160 °C.",
      "Em fogo baixo, aqueça o mel e o azeite (ou óleo) só até ficarem fluidos; tire do fogo e junte a baunilha.",
      "Misture a aveia, as sementes, a chia, o sal, a canela e a fruta seca (se usar).",
      "Despeje o líquido quente e misture bem. Pressione com força numa forma forrada.",
      "Asse por 20 a 25 minutos até dourar. Ainda morna, marque as 10 barras e espere esfriar para soltar.",
    ],
    dicas: [
      "Mel é açúcar: não ultrapasse as 2 colheres no lote inteiro.",
      "Sem fruta seca a barra tem menos carboidrato, o que é preferível no déficit calórico.",
      "Compactar bem é o segredo para não desmanchar.",
      "Porção: 1 barra no meio da manhã; acompanhe de iogurte light se precisar de mais proteína.",
    ],
    nutricao: { kcal: 125, prot: 3, carb: 16, gord: 5, fibras: 3 },
    compras: [
      {
        secao: "Mercearia",
        itens: [
          "Aveia em flocos (140 g)",
          "Mel (≈40 g) ou eritritol",
          "Azeite ou óleo de coco",
          "Sementes de girassol, abóbora e gergelim",
          "Chia ou linhaça",
          "Damasco seco ou cranberry sem açúcar (opcional)",
          "Essência de baunilha",
          "Papel-manteiga",
        ],
      },
      { secao: "Temperos", itens: ["Canela em pó", "Sal"] },
    ],
  },
  {
    id: "docinhos-maca-amendoim-chocolate",
    titulo: "Docinhos de maçã, amendoim e chocolate sem açúcar",
    categoria: "Doces e lanches",
    tags: [
      "sem açúcar",
      "3 ingredientes",
      "doce",
      "chocolate",
      "maça",
    ],
    icone: "imagens/receita-icon-oat-cookie.jpg",
    destaque: "Docinhos sem açúcar adicionado, adoçados naturalmente pela maçã e cobertos de chocolate amargo.",
    ingredientes: [
      {
        itens: [
          "2 maçãs doces",
          "150 g de amendoim torrado sem sal",
          "150 g de chocolate amargo",
          "Canela a gosto (opcional)",
          "1 colher de chá de manteiga (opcional)",
        ],
      },
    ],
    preparo: [
      "Corte as maçãs em pedaços (não precisa descascar) e cozinhe em fogo baixo por cerca de 10 minutos até virar purê; opcionalmente adicione canela e 1 colher de chá de manteiga.",
      "Triture 150 g de amendoim torrado sem sal até virar migalhas (não bata demais para não virar pasta).",
      "Junte o purê de maçã ao amendoim e bata até obter uma massa homogênea; leve à geladeira por cerca de 10 minutos.",
      "Modele bolinhas de cerca de 20 g cada (umedeca as mãos com água se grudar) e leve novamente à geladeira por 10 minutos.",
      "Derreta 150 g de chocolate amargo e cubra cada bolinha; coloque sobre papel manteiga.",
      "Leve à geladeira por cerca de 5 minutos para firmar. Alternativa: enrolar em cacau em pó ou gergelim em vez de chocolate.",
    ],
    dicas: [
      "Escolha maçãs doces para não precisar de açúcar.",
      "Rendimento aproximado: várias bolinhas de ~20 g.",
    ],
    nutricao: "Por doce (~20 g): ~64 kcal; 1,7 g proteína; 4,6 g gordura; 4,5 g carboidrato",
    compras: [],
    fonte: { texto: "YouTube — No SUGAR! Only 3-Ingredient Dessert You Need To Try!", url: "https://www.youtube.com/watch?v=qwi2Y8isloI" },
    rendimento: "várias unidades de ~20 g",
  },
  {
    id: "sobremesa-chia-chocolate-agar",
    titulo: "Sobremesa de chia, linhaça e chocolate com agar-agar",
    categoria: "Doces e lanches",
    tags: [
      "chia",
      "sem açúcar",
      "sem lactose",
      "vegano",
      "proteico",
    ],
    icone: "imagens/receita-icon-oat-cookie.jpg",
    destaque: "Sobremesa de chocolate pronta em minutos, com chia, linhaça e agar-agar — sem açúcar e sem lactose.",
    ingredientes: [
      {
        itens: [
          "1/2 xícara (125 ml) de leite de coco",
          "1/4 xícara (20 g) de cacau em pó",
          "2 colheres de chá de agar-agar",
          "1/4 xícara (60 ml) de água",
          "100 g de chocolate amargo",
          "1 colher de sopa de sementes de chia",
          "1 colher de sopa de linhaça dourada e branca",
        ],
      },
    ],
    preparo: [
      "Misture o leite de coco, o cacau, o agar-agar, a água e o chocolate amargo (conforme o vídeo) até incorporar.",
      "Adicione a chia e a linhaça.",
      "Leve à geladeira por 2 a 3 horas até firmar.",
    ],
    dicas: [
      "Adequada para dietas veganas, sem lactose e sem glúten (conforme descrição do canal).",
    ],
    compras: [],
    fonte: { texto: "YouTube — Ready in 3 minutes! A healthy, protein-rich chia dessert. Sugar-free! Lactose-free!", url: "https://www.youtube.com/watch?v=oFDbeSacXGY" },
  },
  {
    id: "frango-crocante-molho-alho-parmesao",
    titulo: "Frango crocante ao molho cremoso de alho e parmesão",
    categoria: "Pratos principais",
    tags: [
      "frango",
      "molho cremoso",
      "alho",
      "parmesão",
      "mussarela",
    ],
    icone: "imagens/receita-icon-chicken.jpg",
    destaque: "Peito de frango empanado leve em molho cremoso de alho, creme e mussarela, com tomate-cereja.",
    ingredientes: [
      {
        itens: [
          "2 filés de peito de frango",
          "1 colher de chá de sal",
          "1/2 colher de chá de pimenta-do-reino",
          "1 colher de chá de páprica defumada",
          "2 colheres de sopa de farinha de trigo",
          "1 colher de sopa de azeite",
          "1 colher de sopa de manteiga",
          "50 g de queijo mussarela",
          "2 dentes de alho",
          "50 ml de caldo de legumes (~3 colheres de sopa)",
          "200 ml de creme de leite (~3/4 xícara + 1 colher)",
          "Tomates-cereja a gosto",
          "20 g de salsinha",
        ],
      },
    ],
    preparo: [
      "Tempere os filés com sal, pimenta e páprica defumada; passe levemente na farinha.",
      "Doure em azeite e manteiga até ficar dourado e crocante.",
      "Acrescente alho, caldo de legumes e creme de leite; misture até formar molho cremoso.",
      "Adicione a mussarela e deixe derreter no molho.",
      "Finalize com tomates-cereja e salsinha. Sirva quente com massa, purê, arroz ou pão.",
    ],
    dicas: [
      "O título menciona parmesão, mas a lista do vídeo cita mussarela no molho — use o que constar nos ingredientes.",
    ],
    compras: [],
    fonte: { texto: "YouTube — Crispy Chicken in Creamy Garlic Parmesan Sauce 😍 Better Than You Think!", url: "https://www.youtube.com/watch?v=dupbD0MR6Wo" },
  },
  {
    id: "frango-molho-cremoso-cogumelos",
    titulo: "Frango ao molho cremoso de cogumelos",
    categoria: "Pratos principais",
    tags: [
      "frango",
      "cogumelos",
      "molho cremoso",
      "conforto",
    ],
    icone: "imagens/receita-icon-chicken.jpg",
    destaque: "Filés de frango dourados cobertos com molho cremoso de cogumelos, alho e parmesão.",
    ingredientes: [
      {
        titulo: "Frango",
        itens: [
          "560 g (1¼ lb) de peito de frango ou filés",
          "1/2 colher de chá de sal",
          "1/4 colher de chá de pimenta",
          "1/3 xícara (40 g) de farinha",
          "2 colheres de sopa de azeite",
        ],
      },
      {
        titulo: "Molho cremoso de cogumelos",
        itens: [
          "1 colher de sopa (15 ml) de azeite",
          "2 colheres de sopa (30 g) de manteiga",
          "1/2 cebola picada",
          "300 g de cogumelos",
          "3 dentes de alho picados",
          "1 xícara (240 ml) de creme de leite (heavy cream)",
          "3/4 xícara (180 ml) de caldo de legumes ou frango",
          "1/4 xícara (30 g) de parmesão ralado (opcional)",
          "1 colher de chá de raspas de limão",
          "2 colheres de sopa de salsinha picada",
        ],
      },
      {
        titulo: "Para servir",
        itens: [
          "Arroz",
          "Vagem (green beans)",
        ],
      },
    ],
    preparo: [
      "Se usar peito inteiro, corte ao meio na horizontal para formar filés. Seque, tempere com sal e pimenta e passe levemente na farinha.",
      "Doure em 2 colheres de azeite em fogo médio-alto por 3–4 minutos de cada lado (até ~75 °C interno); reserve coberto.",
      "Na mesma panela, baixe o fogo; acrescente 1 colher de azeite e a manteiga. Refogue a cebola 2–3 minutos; adicione os cogumelos e cozinhe 5–7 minutos; acrescente o alho por 30 segundos.",
      "Opcional: deglaceie com 1/4 xícara de vinho branco e deixe evaporar 1–2 minutos.",
      "Adicione o caldo e cozinhe 2 minutos; incorpore o creme, o parmesão e pimenta; cozinhe 3–4 minutos até engrossar levemente.",
      "Volte o frango à panela, banhe com o molho, cozinhe mais 2 minutos, polvilhe salsinha e sirva com arroz e vagem.",
    ],
    dicas: [],
    compras: [],
    fonte: { texto: "YouTube — Creamy Mushroom Chicken | Chicken with Creamy Mushroom Sauce Recipe", url: "https://www.youtube.com/watch?v=0A3e0V3nw2A" },
  },
  {
    id: "wrap-cottage-dois-ingredientes",
    titulo: "Wrap / pão achatado de cottage (2 ingredientes)",
    categoria: "Pães e tortas",
    tags: [
      "cottage",
      "wrap",
      "proteico",
      "low carb",
      "2 ingredientes",
    ],
    icone: "imagens/receita-icon-cheese.jpg",
    destaque: "Wrap ou flatbread low carb só com ovos e queijo cottage — base para sanduíche ou pizza.",
    ingredientes: [
      {
        itens: [
          "2 ovos grandes",
          "1 xícara de queijo cottage (integral, light ou zero)",
          "3/4 colher de chá de alho em pó (temperos a gosto)",
          "1 colher de chá de tempero italiano (a gosto)",
          "Orégano para polvilhar (opcional)",
          "Spray de cozinha / óleo para untar o papel manteiga",
        ],
      },
    ],
    preparo: [
      "No liquidificador ou processador, bata os ovos, o cottage e os temperos até ficar homogêneo.",
      "Forre assadeira com papel manteiga untado; espalhe a mistura no formato desejado (redondo/retangular; mais fino = wrap, mais grosso = flatbread/pizza).",
      "Asse a 175 °C (350 °F) por 30–35 minutos, até as bordas dourarem; wraps mais finos levam menos tempo.",
      "Deixe esfriar completamente antes de descolar.",
      "Para pizza: acrescente molho e coberturas e volte ao forno a ~200 °C (400 °F) por 10–15 minutos.",
    ],
    dicas: [
      "Congela bem.",
      "Dá para fazer vários wraps de uma vez para a semana.",
    ],
    nutricao: "Alto em proteína e baixo em carboidrato (conforme o canal)",
    compras: [],
    fonte: { texto: "YouTube — Easy Cottage Cheese Flatbread or Wraps | 2 Ingredients & High Protein", url: "https://www.youtube.com/watch?v=TH9rWEh8okY" },
  },
  {
    id: "peito-pato-mel-vinho-porto",
    titulo: "Peito de pato laqueado com mel e vinho do Porto",
    categoria: "Pratos principais",
    tags: [
      "pato",
      "magret",
      "mel",
      "vinho do Porto",
      "abóbora",
    ],
    icone: "imagens/receita-icon-chicken.jpg",
    destaque: "Magret de canard laqueado com redução de mel e vinho do Porto, acompanhado de abóbora grelhada na manteiga.",
    ingredientes: [
      {
        itens: [
          "4 peitos de pato (magret) — rende cerca de 4 a 6 pessoas",
          "Vinho do Porto (LBV ou outro) — quantidade para redução (~começar com um pouco e ajustar)",
          "Cerca de 3 colheres de sopa de mel (ajustar ao gosto)",
          "Noz-moscada a gosto",
          "Pimenta-do-reino a gosto",
          "Sal a gosto",
          "Raspas de limão e um pouco de suco de limão",
          "Abóbora para grelhar (acompanhamento)",
          "Manteiga para pincelar a abóbora",
        ],
      },
    ],
    preparo: [
      "Prepare a redução: em uma panela, junte vinho do Porto, mel (~3 colheres de sopa), noz-moscada, suco e raspas de limão (sem a parte branca amarga); reduza até cerca da metade, até ficar mais espesso; reserve.",
      "Limpe os peitos de pato: retire excesso de gordura das laterais e a pelinha dura que encolhe a carne; faça um xadrez só na capa de gordura, sem cortar a carne.",
      "Tempere com sal e pimenta-do-reino.",
      "Aqueça bem uma frigideira; sele primeiro o lado da pele/gordura (drena excesso de gordura se necessário) e depois o outro lado.",
      "Transfira para travessa, pincele com a redução de mel e Porto e leve ao forno pré-aquecido a 180–200 °C por 8–10 minutos.",
      "Deixe a carne descansar ~5–15 minutos antes de fatiar (centro rosado).",
      "Acompanhe com abóbora grelhada pincelada com manteiga e sal.",
    ],
    dicas: [
      "Não passe demais o ponto — peito de pato fica duro se bem passado; o ideal é rosado no centro.",
      "Quantidades exatas de Porto/mel são ao gosto na redução (transcrição não traz ml precisos).",
    ],
    compras: [],
    fonte: { texto: "YouTube — Peito de pato com mel e Vinho do Porto", url: "https://www.youtube.com/watch?v=BkTFTZw9PSE" },
    rendimento: "4 a 6 pessoas",
  },
];
